/**
 * Tests pour buildManifestFromTree — la fonction qui genere un manifest
 * synthetique a partir de l'arborescence d'un repo (fallback quand pas de
 * cursus.yaml).
 *
 * Ne teste pas listRepoTree (necessite Octokit mocke). buildManifestFromTree
 * est exposee separement pour ces tests purs sur structure.
 */
process.env.JWT_SECRET = process.env.JWT_SECRET || 'test-jwt-secret-for-testing-only-32chars!!'

const { buildManifestFromTree } = require('../../../server/services/lumenAutoManifest')
const { parseManifest } = require('../../../server/services/lumenManifest')
const yaml = require('js-yaml')

/** Helper : valide qu'un manifest passe le schema Zod (round-trip via yaml) */
function validateAgainstSchema(manifest) {
  const yamlText = yaml.dump(manifest)
  const parsed = parseManifest(yamlText)
  if (!parsed.ok) throw new Error(`Schema invalide : ${parsed.error}`)
  return parsed.manifest
}

describe('buildManifestFromTree', () => {
  it('arbre vide → chapitre placeholder, pas de crash', () => {
    const m = buildManifestFromTree([], { projectName: 'empty-repo' })
    expect(m.project).toBe('empty-repo')
    expect(m.chapters).toHaveLength(1)
    expect(m.chapters[0].title).toBe('Aucun chapitre')
    expect(m.autoGenerated).toBe(true)
    validateAgainstSchema(m)
  })

  it('README.md racine → premier chapitre "Accueil"', () => {
    const m = buildManifestFromTree(
      [{ path: 'README.md' }, { path: 'cours/01-intro.md' }],
      { projectName: 'test' },
    )
    expect(m.chapters[0]).toEqual({
      title: 'Accueil',
      path: 'README.md',
      section: 'Presentation',
    })
    expect(m.chapters[1].title.toLowerCase()).toContain('intro')
    validateAgainstSchema(m)
  })

  it('profondeur (guides/php/1-intro.md) → section humanisee', () => {
    const m = buildManifestFromTree(
      [{ path: 'guides/php/1-intro.md' }, { path: 'guides/php/2-poo.md' }],
      { projectName: 'test' },
    )
    const sections = new Set(m.chapters.map((c) => c.section))
    expect(sections).toContain('Guides · Php')
    validateAgainstSchema(m)
  })

  it('ignored dirs (node_modules, .github, venv) sont exclus', () => {
    const m = buildManifestFromTree(
      [
        { path: 'README.md' },
        { path: 'node_modules/foo/bar.md' },
        { path: '.github/PULL_REQUEST_TEMPLATE.md' },
        { path: 'venv/lib/site.md' },
        { path: 'cours/01.md' },
      ],
      { projectName: 'test' },
    )
    const paths = m.chapters.map((c) => c.path)
    expect(paths).toContain('README.md')
    expect(paths).toContain('cours/01.md')
    expect(paths.find((p) => p.includes('node_modules'))).toBeUndefined()
    expect(paths.find((p) => p.includes('.github'))).toBeUndefined()
    expect(paths.find((p) => p.includes('venv'))).toBeUndefined()
    validateAgainstSchema(m)
  })

  it('fichiers non-.md (pdf/zip/png) → resources', () => {
    const m = buildManifestFromTree(
      [
        { path: 'README.md' },
        { path: 'guides/cheat.pdf' },
        { path: 'archive.zip' },
        { path: 'images/logo.png' },
      ],
      { projectName: 'test' },
    )
    expect(m.resources).toBeDefined()
    const resourcePaths = m.resources.map((r) => r.path)
    expect(resourcePaths).toContain('guides/cheat.pdf')
    expect(resourcePaths).toContain('archive.zip')
    expect(resourcePaths).toContain('images/logo.png')
    validateAgainstSchema(m)
  })

  it('truncated: true est propage dans le manifest', () => {
    const m = buildManifestFromTree(
      [{ path: 'README.md' }, { path: 'cours/01.md' }],
      { projectName: 'test', truncated: true },
    )
    expect(m.truncated).toBe(true)
    validateAgainstSchema(m)
  })

  it('truncated absent par defaut quand option non passee', () => {
    const m = buildManifestFromTree([{ path: 'README.md' }], { projectName: 'test' })
    expect(m.truncated).toBeUndefined()
    validateAgainstSchema(m)
  })

  it('sorting : prefixe numerique avant alphabetique', () => {
    const m = buildManifestFromTree(
      [
        { path: 'cours/zebra.md' },
        { path: 'cours/02-second.md' },
        { path: 'cours/10-tenth.md' },
        { path: 'cours/01-first.md' },
        { path: 'cours/abracadabra.md' },
      ],
      { projectName: 'test' },
    )
    // Les chapitres sous cours/ sont ordonnes par prefixe numerique puis alpha
    const cours = m.chapters.filter((c) => c.path.startsWith('cours/'))
    expect(cours[0].path).toBe('cours/01-first.md')
    expect(cours[1].path).toBe('cours/02-second.md')
    expect(cours[2].path).toBe('cours/10-tenth.md')
    // abracadabra < zebra alpha
    expect(cours[3].path).toBe('cours/abracadabra.md')
    expect(cours[4].path).toBe('cours/zebra.md')
    validateAgainstSchema(m)
  })

  it('aucun .md → chapitre placeholder, manifest valide quand meme', () => {
    const m = buildManifestFromTree(
      [{ path: 'data.json' }, { path: 'image.png' }],
      { projectName: 'binary-only' },
    )
    expect(m.chapters).toHaveLength(1)
    expect(m.chapters[0].path).toBe('README.md')
    expect(m.chapters[0].title).toBe('Aucun chapitre')
    validateAgainstSchema(m)
  })
})
